// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu0fLWEyInnAxina0CcS-zNqu2h40TBFM',
    appId: '1:451861629786:web:96b7903d0c1dbf398a0163',
    messagingSenderId: '451861629786',
    projectId: 'flutter-7125c',
    authDomain: 'flutter-7125c.firebaseapp.com',
    storageBucket: 'flutter-7125c.firebasestorage.app',
    measurementId: 'G-2GKPX8XRBH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX91A0Mfc5QwJ3Nlm5Su-hAejSJQ_Jmp8',
    appId: '1:451861629786:android:05f16394c784244a8a0163',
    messagingSenderId: '451861629786',
    projectId: 'flutter-7125c',
    storageBucket: 'flutter-7125c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh_J0V3bOxMUjpRwA7HtrrCiE9agOMj10',
    appId: '1:451861629786:ios:3376e819848015288a0163',
    messagingSenderId: '451861629786',
    projectId: 'flutter-7125c',
    storageBucket: 'flutter-7125c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
